name: default
run-name: default
on:
    push:
        branches:
        - main
        - 'releases/**'
jobs:
    default:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
