name: default
run-name: default
on:
    push:
        branches:
        - test
jobs:
    default:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install asdf & tools
                uses: asdf-vm/actions/install@v4
            -   name: Chack bun version
                run: bun --version
            -   name: Install dependencies
                run: bun install
