name: test
run-name: test
on:
    push:
        branches:
            - test

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Install mise & tools
              uses: jdx/mise-action@v2
            - run: |
                  git add ./*.user.css -f
                  git restore --staged .github/workflows || true
                  git checkout -- .github/workflows || true
            - name: Upload compiled files
              uses: actions-go/push@v1
              with:
                  author-name: github-actions[bot]
                  author-email: github-actions[bot]@users.noreply.github.com
                  commit-message: 'Add compiled files'
                  fail-if-empty: true
                  create-commit: true
