name: test
run-name: test
on:
    push:
        branches:
            - test
    pull_request:
        branches:
            - test

permissions:
    contents: write
    issues: write
    pull-requests: write

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                fetch-depth: 0
            - name: Install mise & tools
              uses: jdx/mise-action@v3
            - name: Add compiled files to commit
              run:  git add ./*.user.css -f
            - name: Upload compiled files
              uses: actions-go/push@v1
              with:
                author-name: github-actions[bot]
                author-email: github-actions[bot]@users.noreply.github.com
                commit-message: '[github actions bot] Add compiled files'
                create-commit: true
            - name: MegaLinter
              uses: oxsecurity/megalinter@v8
              id: ml
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                MEGALINTER_CONFIG: .github/.mega-linter.yml
                EXTENDS: .github/.mega-linter.yml
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                name: MegaLinter reports
                include-hidden-files: 'true'
                path: |
                    megalinter-reports
                    mega-linter.log
            - name: Upload fixed files
              uses: actions-go/push@v1
              with:
                author-name: megalinter-bot
                author-email: 129584137+megalinter-bot@users.noreply.github.com
                commit-message: '[MegaLinter] Apply linters fixes'
                create-commit: true
