name: test
run-name: test
on:
    push:
        branches:
        - test
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Install mise & tools
                uses: jdx/mise-action@v2
            -   name: Chack bun version
                run: bun --version
            -   name: Install dependencies
                run: bun install
            -   name: Upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    path: ./*.user.css
                    name: styles
                    if-no-files-found: error
                    overwrite: true
